"""Second migration

Revision ID: 72dcf7d343fa
Revises: 
Create Date: 2017-02-16 11:34:14.494200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72dcf7d343fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Store_Retrieve', ['location'])
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'Store_Retrieve', type_='unique')
    # ### end Alembic commands ###
